<div id="paymentFrame1" class="span4">

    <button id="pgButton_man1">Сплатити 1</button>
    <button id="pgButton_man2">Сплатити 2</button>

    <script src="https://www.portmone.com.ua/r3/resources/pg/js/asset/pg.min.js?v=15092019"></script>
    <script type="text/javascript" id="portmone-script">
        var data1 = {
            paymentTypes: { card: "Y", gpay: "Y" },
            priorityPaymentTypes: { card: "1", gpay: "2" },
            payee: {
                payeeId: "1185",
            },
            payer: {
                lang: "uk",
            },
            goods: [
                {
                    internalCode: "ЦБ208406",
                    manufacturerCode: "92949",
                    govClassificationCode: "8708803598",
                    name: "ВАЖІЛЬ ПІДВІСКИ передній правий Logan II",
                    name_en: "something Logan II",
                    description: "Сірий, залізний",
                    description_en: "Gray, iron",
                    price: "1.6",
                    quantity: "2",
                    uomCode: "",
                    amount: "3.2",
                    serviceFlag: "N",
                    taxRateCodes: "A",
                    descriptionUrl: "",
                    imageUrl: "",
                },
            ],
            order: { billAmount: "3.2" },
            closeModal: "N",
            frameHolderId: "paymentFrame1",
        };
        var brand = {
            height: "40px",
            width: "150px",
            buttoncolor: "#FF0000",
            fontfamily: "Open Sans",
            textcolor: "#FFF",
            lang: "uk",
            padding: "5px",
            border: "1px solid grey",
            fontsize: "14px",
            closemodal: "Y",
        };
       /* PG.success(function (data) {
            console.log(JSON.stringify(data));
        });*/
        // PG.paymentData("gateway", data, 'frame');
        // PG.brandButton(brand);

        var data2 = {
            paymentTypes: { card: "Y", gpay: "Y" },
            priorityPaymentTypes: { card: "1", gpay: "2" },
            payee: {
                payeeId: "1185",
            },
            payer: {
                lang: "uk",
            },
            goods: [
                {
                    internalCode: "ЦБ208406",
                    manufacturerCode: "92949",
                    govClassificationCode: "8708803598",
                    name: "ВАЖІЛЬ ПІДВІСКИ передній правий Logan II",
                    name_en: "something Logan II",
                    description: "Сірий, залізний",
                    description_en: "Gray, iron",
                    price: "1.6",
                    quantity: "3",
                    uomCode: "",
                    amount: "4.8",
                    serviceFlag: "N",
                    taxRateCodes: "A",
                    descriptionUrl: "",
                    imageUrl: "",
                },
            ],
            order: { billAmount: "4.8" },
            closeModal: "N",
            frameHolderId: "paymentFrame1",
        };

        PG.success(function (data) {
            console.log(JSON.stringify(data));
        });

        const button1 = document.querySelector('#pgButton_man1');
        button1.addEventListener('click', () => {
            console.log('click 1');

            PG.setButtonId('pgButton_man1');
            PG.paymentData("gateway",data1,"frame"); PG.create();



        });

        // Select the element
        const button2 = document.querySelector('#pgButton_man2');
        button2.addEventListener('click', () => {
            console.log('click 2');

            PG.setButtonId('pgButton_man2');
            PG.paymentData("gateway",data2,"frame"); PG.create();

        });

        // PG.paymentData("gateway", data, 'frame');
        // PG.brandButton(brand);

    </script>


</div>